version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - db
    ports:
      - "10000:7000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: mydatabase
      EMAIL_USER: 'usefulspanish@mail.ru'
      EMAIL_PASS: 'gz41Q31mxscMhtz6H30u'
      PORT: 7000

volumes:
  postgres_data:
